### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{.../com.freshplanet.googleplaygames.SignInActivity}: 

### ISSUE THREAD

**Issue by kubusabadi** [freshplanet/ANE-Google-Play-Game-Services#12]
Hi guys! I have released my game already, because everything seemed to be ok, but after some users intalled it, I have started to receive crashes:

java.lang.RuntimeException: Unable to start activity ComponentInfo{.../com.freshplanet.googleplaygames.SignInActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1657)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1673)
at android.app.ActivityThread.access$1500(ActivityThread.java:119)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:941)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3698)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.freshplanet.googleplaygames.SignInActivity.onCreate(SignInActivity.java:17)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1621)
... 11 more

and

jjava.lang.RuntimeException: Unable to start activity ComponentInfo{../com.freshplanet.googleplaygames.SignInActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1815)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1831)
at android.app.ActivityThread.access$500(ActivityThread.java:122)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1024)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:132)
at android.app.ActivityThread.main(ActivityThread.java:4123)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:491)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.freshplanet.googleplaygames.GameHelper.showFailureDialog(GameHelper.java:994)
at com.freshplanet.googleplaygames.GameHelper.beginUserInitiatedSignIn(GameHelper.java:644)
at com.freshplanet.googleplaygames.SignInActivity.onStart(SignInActivity.java:44)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1132)
at android.app.Activity.performStart(Activity.java:4407)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1788)
... 11 more

Can you help me fix the issue? Have you faced something like that?

**Comment by JokerDen** [comment]
Problem is still actual.
