### ISSUE TITLE
Hi,  sign in crashed.

### ISSUE THREAD

**Issue by lovewqcm520** [freshplanet/ANE-Google-Play-Game-Services#2]
Hi, I try the ane on android 4.0.3, when i try to sign in, first time receive failed event, then i sign in again, and my phone open the window to let me choose which account to login(My phone have multiple Google account), so i choose one account that already register as a test account, the app that use ane just crashed, no respond at all.

**Comment by skliarovartem** [comment]
problem here.
it creash when i try ti initialize ane. In ddms i see fatal error:
11-17 18:58:44.939: I/[AirGooglePlayGames](13504): sign in activiy started
11-17 18:58:44.939: I/[AirGooglePlayGames](13504): hasExtra
11-17 18:58:44.939: I/[AirGooglePlayGames](13504): shouldStartSignInFlow : false
11-17 18:58:44.939: I/[AirGooglePlayGames](13504): shouldStartSignInFlow2 : false
11-17 18:58:44.939: I/[AirGooglePlayGames](13504): create helper
11-17 18:58:44.949: W/dalvikvm(13504): DexOpt: method is in an interface
11-17 18:58:44.949: I/dalvikvm(13504): Could not find method com.google.android.gms.common.api.GoogleApiClient.isConnected, referenced from method com.freshplanet.googleplaygames.GameHelper.beginUserInitiatedSignIn
11-17 18:58:44.949: W/dalvikvm(13504): VFY: unable to resolve virtual method 5464: Lcom/google/android/gms/common/api/GoogleApiClient;.isConnected ()Z
11-17 18:58:44.949: W/dalvikvm(13504): VFY:  rejecting opcode 0x6e at 0x0010
11-17 18:58:44.949: W/dalvikvm(13504): VFY:  rejected Lcom/freshplanet/googleplaygames/GameHelper;.beginUserInitiatedSignIn ()V
11-17 18:58:44.949: W/dalvikvm(13504): Verifier rejected class Lcom/freshplanet/googleplaygames/GameHelper;
11-17 18:58:44.949: D/AndroidRuntime(13504): Shutting down VM
11-17 18:58:44.949: W/dalvikvm(13504): threadid=1: thread exiting with uncaught exception (group=0x41e8d930)
11-17 18:58:44.949: E/AndroidRuntime(13504): FATAL EXCEPTION: main
11-17 18:58:44.949: E/AndroidRuntime(13504): java.lang.VerifyError: com/freshplanet/googleplaygames/GameHelper
11-17 18:58:44.949: E/AndroidRuntime(13504):    at com.freshplanet.googleplaygames.ExtensionContext.createHelperIfNeeded(Unknown Source)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at com.freshplanet.googleplaygames.SignInActivity.onCreate(Unknown Source)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at android.app.Activity.performCreate(Activity.java:5326)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2306)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at android.app.ActivityThread.access$700(ActivityThread.java:153)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at android.os.Handler.dispatchMessage(Handler.java:99)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at android.os.Looper.loop(Looper.java:176)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at android.app.ActivityThread.main(ActivityThread.java:5302)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at java.lang.reflect.Method.invokeNative(Native Method)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at java.lang.reflect.Method.invoke(Method.java:511)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
11-17 18:58:44.949: E/AndroidRuntime(13504):    at dalvik.system.NativeStart.main(Native Method)
